%YAML:1.0

# Close/Far threshold. Baseline times.
ThDepth: 35.0
#--------------------------------------------------------------------------------------------
# Feature extraction parameters
#--------------------------------------------------------------------------------------------
FeaturExtrac.detectorType: 0 # 0: ORB, 1: SuperPoint
#--------------------------------------------------------------------------------------------
# Stereo Matching parameters
#--------------------------------------------------------------------------------------------
Disparity.maxdisp: 128 # a default parameter can be the camera matrix fx value
Disparity.mindisp: 0  # minDisp < disp <= maxDisp

SAD.winHalfBlockSize: 2
SAD.minValue: 0.04

#--------------------------------------------------------------------------------------------
# KLT parameters
#--------------------------------------------------------------------------------------------
KLT.winSize: 15     # Size (winSize,winSize)
KLT.pyrMaxLevel: 4

#--------------------------------------------------------------------------------------------
# Non maximum suppression parameters
#--------------------------------------------------------------------------------------------

#Size of cells in NMS
FeaturExtrac.frameGridCols: 24
FeaturExtrac.frameGridRows: 24

#--------------------------------------------------------------------------------------------
# 8-point algorithm parameters
#--------------------------------------------------------------------------------------------

#Eight Point algorithm: probability of not all N points are inliers
EightPoint.ransacProb: 0.99

#Eight Point algorithm: number of points in ransac iteration
EightPoint.ransacSet: 8

#Eight Point algorithm: maximum number of iteration in ransac
EightPoint.ransacMaxInt: 200

#Eight Point algorithm: threshold to define a point as a inlier
EightPoint.ransacTh: 3.0

#--------------------------------------------------------------------------------------------
# Linear triangulation parameters
#--------------------------------------------------------------------------------------------

#Linear triangulation: threshold for reprojection error, points with high reprojection error are discarded
Triangulation.reproTh: 0.5

#Linear triangulation: number iteration in the 3D point estimation.
Triangulation.maxIt: 1

#--------------------------------------------------------------------------------------------
# Gauss Newton pose estimation parameters
#--------------------------------------------------------------------------------------------

#Gauss Newton pose estimation: ransac probability of not all N points are inliers
GN.ransacProb: 0.99

#Gauss Newton pose estimation: ransac threshold to define a point as inlier
GN.ransacTh: 1.5

#Gauss Newton pose estimation: ransac minimum set for model estimation
GN.ransacMinSet: 3

#Gauss Newton pose estimation: ransac number of iteration
GN.ransacMaxIt: 50

#Gauss Newton pose estimation: maximum iteration of GN optimization
GN.maxIt: 50

#Gauss Newton pose estimation: maximum iteration for pose refinment
GN.finalMaxIt: 50

#Gauss Newton reprojection weight adjust value, it depends on the stereo camera and lens setup, empirically set
GN.reweigh: true
GN.weightAdjustVal: 0.011


#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.Camera.width: 752
Viewer.Camera.height: 480
Viewer.Camera.fps: 30.0
Viewer.ViewpointX: -1
Viewer.ViewpointY: 1
Viewer.ViewpointZ: -1
Viewer.ViewpointF: 420


#--------------------------------------------------------------------------------------------
# SuperPoint Parameters
#--------------------------------------------------------------------------------------------
SuperPoint.modelPath: /root/kltvo/superpoint_v1.pt
SuperPoint.nms: true
SuperPoint.nmsDistance: 4
SuperPoint.threshold: 0.2
SuperPoint.cuda: true
